version: '3.7'

services:

  csc-front:
    container_name: csc-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - csc_api
    # stdin_open: true
networks:
  csc_api :
    external: true  